name: ios

on:
  push:
    paths: ["ios/**"]
  pull_request:
    paths: ["ios/**"]

jobs:
  build-testflight:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: "15.4"
      - name: Cache CocoaPods
        uses: actions/cache@v4
        with:
          path: ~/Library/Caches/CocoaPods
          key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
      - name: Install dependencies
        run: |
          sudo gem install bundler
          bundle install --path vendor/bundle
          cd ios && bundle exec pod install
      - name: Build & upload to TestFlight
        run: |
          cd ios && bundle exec fastlane ios beta
        env:
          APP_STORE_CONNECT_API_KEY_BASE64: ${{ secrets.ASC_API_KEY }}
